name: MohistSchematics
main: fr.oceanwars.fastschematics.MohistSchematics
version: 1.0.2
commands:
  mcopy:
    description: "Allow you create a schematic"
    usage: "/<command> pos1|pos2|save|load|paste"
    aliases: ["/mc"]
    permission: mohistschematics.admin
